# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cd67eaa7fde5e46f3d7f9d5f07e2e4f23e295ba74cb736dd8906c4c892ae02c2fe12e25ca0f0c1830520a7aff2c037272ee59a66d9171a6fdcfe3248d9a1d14

test:
  secret_key_base: 307816ee4086c2d891da573dc81e46d32bf0d8d1f5a13b6d0dc28635b4e65fedf6df5583543ecc6865658e6286f69876a234a5f4397d8247097f118b8c2c9a0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
